### ISSUE TITLE
[Chore] Build the infra for this project

### ISSUE THREAD

**Issue by qrtt1** [qtysdk/stock-info#1]
Acceptance criteria:

* Implement a basic AWS Lambda function that returns `{"Hello": "World"}` regardless of the input.
* Create a GitHub Action that deploys a new version to AWS Lambda whenever a new version tag is added.

## Tasks

- [x] lambda function
- [x] bootstrap it manually and write the note (will improve it later)
- [x] deploy it automatically from the GitHub Action

**Comment by qtysdk** [comment]
Finish the issue, check the review 
https://youtu.be/-fL1TIlYqXc?si=LAdsnpnZyXgErcNI
