### ISSUE TITLE
[Feature] build the first use-case for 0056

### ISSUE THREAD

**Issue by qtysdk** [qtysdk/stock-info#2]
## Acceptance criteria
* Design a function to get `stock number` as the input and output
  * 股利 dividend
  * 除息日 exDividendDate
  * 股利發放日 dividendPaymentDate

### non-functional requirements

* Don't implement in the lambda function directly, it must be working at local 
* It is time to add tests

## Example

The first example is `0056`

Please collect information from:
https://www.yuantafunds.com/myfund/dividend?fundid=1084
<img width="1142" alt="image" src="https://github.com/qtysdk/stock-info/assets/6507277/15635a39-50b6-4396-a01d-71e2fac2e0f1">

**Comment by qrtt1** [comment]
## Review 

完成 `0056` 資料下載的實作。由於這是第 1 個支援的 ETF，有一些基本的設計會在這裡同時進行。

## Request 與 Response

當 Lambda Function 無法順利獲得結果時，會在 `result` 內回傳 `success=false` 的值：

```json
{
  "version": "0.1.2",
  "result": {
    "success": false,
    "stock_number": "0000",
    "dividend": 0,
    "exDividendDate": "",
    "dividendPaymentDate": ""
  }
}
```

只要 Input 格式不合，或是無法取得資料的情況都應該是這個結果。

### 實測 0056

Request:

```json
{"stock_number": "0056"}
```

Response:

```json
{
  "version": "0.1.2",
  "result": {
    "success": true,
    "stock_number": "0056",
    "dividend": 0.7,
    "exDividendDate": "2024/01/17",
    "dividendPaymentDate": "2024/02/21"
  }
}
```

### 實測 00878

由於 `00878` 還沒有支援，它會因為 exception 而失敗

Request:

```json
{"stock_number": "00878"}
```

Response:

```json
{
  "version": "0.1.3",
  "result": {
    "success": false,
    "stock_number": "00878",
    "dividend": 0,
    "exDividendDate": "",
    "dividendPaymentDate": ""
  }
}
```
